---
http_interactions:
- request:
    method: get
    uri: https://fakestoreapi.com/products/1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v1.10.3
  response:
    status:
      code: 200
      message: OK
    headers:
      date:
      - Wed, 28 Aug 2024 19:23:40 GMT
      content-type:
      - application/json; charset=utf-8
      transfer-encoding:
      - chunked
      connection:
      - keep-alive
      access-control-allow-origin:
      - "*"
      etag:
      - W/"16c-MMdrqY6N0sTiefLdsgtBej9eunY"
      x-powered-by:
      - Express
      cf-cache-status:
      - DYNAMIC
      report-to:
      - '{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=MOO4SkTzb5s9HlF4pIjbaIw3zxlji1jERiuus1OpGKdEGwO3xVh%2B%2BkxFV5sqrPSFjddyxDGmPhx0w9IhyLTlU6%2FsVAq5e08JdJPvv1IVwdaQrOy0V4TBYFgYfPev27OgpYf2"}],"group":"cf-nel","max_age":604800}'
      nel:
      - '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'
      server:
      - cloudflare
      cf-ray:
      - 8ba6ad548a540c42-DME
      alt-svc:
      - h3=":443"; ma=86400
    body:
      encoding: ASCII-8BIT
      string: '{"id":1,"title":"Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops","price":109.95,"description":"Your
        perfect pack for everyday use and walks in the forest. Stash your laptop (up
        to 15 inches) in the padded sleeve, your everyday","category":"men''s clothing","image":"https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg","rating":{"rate":3.9,"count":120}}'
  recorded_at: Wed, 28 Aug 2024 19:23:40 GMT
recorded_with: VCR 6.2.0
